import { logout } from "../api/auth.service";

export const IMAGES = {
    splashSyan : require("../assets/images/splah-logo-syan.png"),
    onboarding1 : require("../assets/images/onboarding-1.png"),
    onboarding2 : require("../assets/images/onboarding-2.png"),
    onboarding3 : require("../assets/images/onboarding3.png"),
    onboarding4 : require("../assets/images/onboarding4.png"),
    headerIcons : require("../assets/images/header-syan.png"),
    userInput: require("../assets/images/user-input.png"),
    lockInput: require("../assets/images/lock-input.png"),
    emailInput: require("../assets/images/email-input.png"),
    gridHome : require("../assets/images/grid-home.png"),
    homeImage1: require("../assets/images/home_image1.png"),
    homeImage2: require("../assets/images/home_image2.png"),
    cross_icon: require("../assets/images/cross_icons.png"),
    quiz_image: require("../assets/images/quiz_image.png"),
    video_icon: require("../assets/images/video_icon.png"),
    notes_icon: require("../assets/images/notes_icon.png"),
    profile_img: require("../assets/images/profile.png"),
    courses_pic1: require("../assets/images/courses_pic1.png"),
    icon_unlock: require("../assets/images/icon_unlock.png"),
    icon_lock: require("../assets/images/icon_lock.png"),
    icon_group: require("../assets/images/icon_group.png"),
    icon_clock : require("../assets/images/icon_clock.png"),
    courses_pic2: require("../assets/images/courses_pic2.png"),
    courses_pic3: require("../assets/images/courses_image3.png"),
    icon_cells: require("../assets/images/icon_cells.png"),
    icon_blood: require("../assets/images/icon_blood.png"),
    icon_nerve: require("../assets/images/icon_nerve.png"),
    icon_video: require("../assets/images/icon_video.png"),
    icon_readnotes: require("../assets/images/icon_readnotes.png"),
    icon_skull: require("../assets/images/icon_skull.png"),
    icon_circle_complete: require("../assets/images/icon_circle_complete.png"),
    icon_circle: require("../assets/images/icon_circle.png"),
    libraryImage: require("../assets/images/libraryImage.png"),
    drawer_calender: require("../assets/images/drawer_calender.png"),
    drawer_chat: require("../assets/images/drawer_chat.png"),
    drawer_favorite: require("../assets/images/drawer_favorite.png"),
    drawer_overview: require("../assets/images/drawer_overview.png"),
    drawer_quiz: require("../assets/images/drawer_quiz.png"),
    drawer_video: require("../assets/images/drawer_video.png"),
    drawer_settings : require("../assets/images/drawer_settings.png"),
    drawer_editProfile : require("../assets/images/drawer_editProfile.png"),
    drawer_security : require("../assets/images/drawer_security.png"),
    drawer_subscription : require("../assets/images/drawer_subscription.png"),
    drawer_invoice : require("../assets/images/drawer_invoice.png"),
    joined_chat: require("../assets/images/joined_chat.png"),
    joined_chat_btm1: require("../assets/images/joined_chat_btm1.png"),
    joined_chat_btm2: require("../assets/images/joined_chat_btm2.png"),
    complete_your_profile: require("../assets/images/syan_complete_your_profile.png"),
    logout_icon: require("../assets/images/logout.png"),
}