export type DrawerParamList = {
    openDrawer: undefined;
    Home: undefined;
    Courses:undefined;
    QuizHistory:undefined;
    VideoHistory:undefined;
    NotesHistory:undefined;
    Profile:undefined;
    Security:undefined;
    Subscriptions:undefined;
    Invoices:undefined;
    Modules:undefined;
    Lecture:undefined;
    Vidoes:undefined;
    ReadNotes:undefined;
    Quiz:undefined;
    Anatomy:undefined;
    QuizCourses:undefined;
    SelectQuiz:undefined;
    Library:undefined;
    Notes:undefined;
    FavoriteQuiz:undefined;
    FavoriteVideos:undefined;
    Favorite:undefined;
    ChatForum:undefined;
    QuizWarning:undefined;
    CreateQuiz:undefined;
    Question:undefined;
    QuizResult:undefined;
    QuizExplanations:undefined;
    QuizExplanationsDetails:undefined;
    Videos:undefined;
    FavoriteNotes:undefined;
    StackNavigator:undefined;
};